// source: proto/clarifai/api/utils/time.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.clarifai.api.utils.TimeOfDay', null, global);
goog.exportSymbol('proto.clarifai.api.utils.TimeOfDayRange', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.clarifai.api.utils.TimeOfDay = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.clarifai.api.utils.TimeOfDay, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.clarifai.api.utils.TimeOfDay.displayName = 'proto.clarifai.api.utils.TimeOfDay';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.clarifai.api.utils.TimeOfDayRange = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.clarifai.api.utils.TimeOfDayRange, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.clarifai.api.utils.TimeOfDayRange.displayName = 'proto.clarifai.api.utils.TimeOfDayRange';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.clarifai.api.utils.TimeOfDay.prototype.toObject = function(opt_includeInstance) {
  return proto.clarifai.api.utils.TimeOfDay.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.clarifai.api.utils.TimeOfDay} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.clarifai.api.utils.TimeOfDay.toObject = function(includeInstance, msg) {
  var f, obj = {
    hours: jspb.Message.getFieldWithDefault(msg, 1, 0),
    minutes: jspb.Message.getFieldWithDefault(msg, 2, 0),
    seconds: jspb.Message.getFieldWithDefault(msg, 3, 0),
    nanos: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.clarifai.api.utils.TimeOfDay}
 */
proto.clarifai.api.utils.TimeOfDay.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.clarifai.api.utils.TimeOfDay;
  return proto.clarifai.api.utils.TimeOfDay.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.clarifai.api.utils.TimeOfDay} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.clarifai.api.utils.TimeOfDay}
 */
proto.clarifai.api.utils.TimeOfDay.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHours(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMinutes(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSeconds(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNanos(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.clarifai.api.utils.TimeOfDay.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.clarifai.api.utils.TimeOfDay.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.clarifai.api.utils.TimeOfDay} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.clarifai.api.utils.TimeOfDay.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHours();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMinutes();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSeconds();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getNanos();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional int32 hours = 1;
 * @return {number}
 */
proto.clarifai.api.utils.TimeOfDay.prototype.getHours = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.clarifai.api.utils.TimeOfDay} returns this
 */
proto.clarifai.api.utils.TimeOfDay.prototype.setHours = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 minutes = 2;
 * @return {number}
 */
proto.clarifai.api.utils.TimeOfDay.prototype.getMinutes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.clarifai.api.utils.TimeOfDay} returns this
 */
proto.clarifai.api.utils.TimeOfDay.prototype.setMinutes = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 seconds = 3;
 * @return {number}
 */
proto.clarifai.api.utils.TimeOfDay.prototype.getSeconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.clarifai.api.utils.TimeOfDay} returns this
 */
proto.clarifai.api.utils.TimeOfDay.prototype.setSeconds = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 nanos = 4;
 * @return {number}
 */
proto.clarifai.api.utils.TimeOfDay.prototype.getNanos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.clarifai.api.utils.TimeOfDay} returns this
 */
proto.clarifai.api.utils.TimeOfDay.prototype.setNanos = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.toObject = function(opt_includeInstance) {
  return proto.clarifai.api.utils.TimeOfDayRange.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.clarifai.api.utils.TimeOfDayRange} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.clarifai.api.utils.TimeOfDayRange.toObject = function(includeInstance, msg) {
  var f, obj = {
    start: (f = msg.getStart()) && proto.clarifai.api.utils.TimeOfDay.toObject(includeInstance, f),
    end: (f = msg.getEnd()) && proto.clarifai.api.utils.TimeOfDay.toObject(includeInstance, f),
    isStartInclusive: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    isEndInclusive: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.clarifai.api.utils.TimeOfDayRange}
 */
proto.clarifai.api.utils.TimeOfDayRange.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.clarifai.api.utils.TimeOfDayRange;
  return proto.clarifai.api.utils.TimeOfDayRange.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.clarifai.api.utils.TimeOfDayRange} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.clarifai.api.utils.TimeOfDayRange}
 */
proto.clarifai.api.utils.TimeOfDayRange.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.clarifai.api.utils.TimeOfDay;
      reader.readMessage(value,proto.clarifai.api.utils.TimeOfDay.deserializeBinaryFromReader);
      msg.setStart(value);
      break;
    case 2:
      var value = new proto.clarifai.api.utils.TimeOfDay;
      reader.readMessage(value,proto.clarifai.api.utils.TimeOfDay.deserializeBinaryFromReader);
      msg.setEnd(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsStartInclusive(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsEndInclusive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.clarifai.api.utils.TimeOfDayRange.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.clarifai.api.utils.TimeOfDayRange} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.clarifai.api.utils.TimeOfDayRange.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStart();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.clarifai.api.utils.TimeOfDay.serializeBinaryToWriter
    );
  }
  f = message.getEnd();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.clarifai.api.utils.TimeOfDay.serializeBinaryToWriter
    );
  }
  f = message.getIsStartInclusive();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getIsEndInclusive();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional TimeOfDay start = 1;
 * @return {?proto.clarifai.api.utils.TimeOfDay}
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.getStart = function() {
  return /** @type{?proto.clarifai.api.utils.TimeOfDay} */ (
    jspb.Message.getWrapperField(this, proto.clarifai.api.utils.TimeOfDay, 1));
};


/**
 * @param {?proto.clarifai.api.utils.TimeOfDay|undefined} value
 * @return {!proto.clarifai.api.utils.TimeOfDayRange} returns this
*/
proto.clarifai.api.utils.TimeOfDayRange.prototype.setStart = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.clarifai.api.utils.TimeOfDayRange} returns this
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.clearStart = function() {
  return this.setStart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.hasStart = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TimeOfDay end = 2;
 * @return {?proto.clarifai.api.utils.TimeOfDay}
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.getEnd = function() {
  return /** @type{?proto.clarifai.api.utils.TimeOfDay} */ (
    jspb.Message.getWrapperField(this, proto.clarifai.api.utils.TimeOfDay, 2));
};


/**
 * @param {?proto.clarifai.api.utils.TimeOfDay|undefined} value
 * @return {!proto.clarifai.api.utils.TimeOfDayRange} returns this
*/
proto.clarifai.api.utils.TimeOfDayRange.prototype.setEnd = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.clarifai.api.utils.TimeOfDayRange} returns this
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.clearEnd = function() {
  return this.setEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.hasEnd = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool is_start_inclusive = 3;
 * @return {boolean}
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.getIsStartInclusive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.clarifai.api.utils.TimeOfDayRange} returns this
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.setIsStartInclusive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool is_end_inclusive = 4;
 * @return {boolean}
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.getIsEndInclusive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.clarifai.api.utils.TimeOfDayRange} returns this
 */
proto.clarifai.api.utils.TimeOfDayRange.prototype.setIsEndInclusive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


goog.object.extend(exports, proto.clarifai.api.utils);
