name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Prepare the API keys & run tests
      env:
        CLARIFAI_USER_EMAIL: ${{ secrets.CLARIFAI_USER_EMAIL }}
        CLARIFAI_USER_PASSWORD: ${{ secrets.CLARIFAI_USER_PASSWORD }}
        CI: true  # According to docs, setting this env. var. is required.
      shell: bash
      run: |
        export CLARIFAI_APP_ID="$(python scripts/app_and_key_for_tests.py --create-app javascript-github)"
        export CLARIFAI_API_KEY="$(python scripts/app_and_key_for_tests.py --create-key ${CLARIFAI_APP_ID})"
        python scripts/app_and_key_for_tests.py --create-workflow ${CLARIFAI_API_KEY}
        npm test
        python scripts/app_and_key_for_tests.py --delete-app ${CLARIFAI_APP_ID}
    - name: Slack Notify
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_ICON: "https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png"
        SLACK_USERNAME: "GitHub Alerts"
        SLACK_CHANNEL: "#grpc-client-repo-alerts"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: "Test failure"
        SLACK_FOOTER: "Clarifai NodeJS GRPC Repo"
